# Generated by Django 5.1.15 on 2026-07-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('name_ar', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'wilayas',
                'ordering': ['code'],
            },
        ),
    ]
