# Generated by Django 5.1.15 on 2026-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='International format without +, e.g. 213550000000', max_length=20)),
                ('store_name', models.CharField(default='AV Parfums', max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'store settings',
                'verbose_name_plural': 'store settings',
            },
        ),
    ]
