# Generated by Django 5.1.15 on 2026-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='vip_threshold',
            field=models.DecimalField(decimal_places=2, default=20000, help_text='Total spend (DA) above which a customer is flagged VIP.', max_digits=10),
        ),
    ]
