# Generated by Django 5.1.15 on 2026-07-24 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Detail-page view counter.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of revenue, for automatic margin.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = entrée, négative = sortie.')),
                ('resulting_stock', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('restock', 'Réapprovisionnement'), ('correction', "Correction d'inventaire"), ('damage', 'Casse / perte'), ('return', 'Retour client')], default='restock', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
